baseurl = "https://reorchestrate.com/"
title = "reorchestrate"
author = "Mike Seddon"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsUseClasses = true
pygmentsStyle = "default"
pygmentsCodefences = true

[params]
  sitename = "reorchestrate"

  dateFormat = "2 January 2006"

[[params.social]]
  url = "https://github.com/seddonm1"
  fa_icon = "fa-github"