baseurl = "https://reorchestrate.com/"
title = "reorchestrate"
author = "Mike Seddon"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    style = "default"

[params]
  source = "https://github.com/seddonm1/seddonm1.github.io/blob/main/content/posts/"
  dateFormat = "2 January 2006"