baseurl = "https://reorchestrate.com/"
title = "reorchestrate"
author = "Mike Seddon"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    style = "default"

[params]
  source = "https://github.com/seddonm1/seddonm1.github.io/blob/main/content/posts/"
  dateFormat = "2 January 2006"

[[params.social]]
  url = "https://github.com/seddonm1"
  fa_icon = "fa-github"